src/SCRIPTS/RF/PAGES/rxrf.lua
=> rxrf.lua refactored for refactored MSP_RX_CONFIG message

src/SCRIPTS/RF/PAGES/failsafe.lua, src/SCRIPTS/RF/PAGES/filters.lua, src/SCRIPTS/RF/PAGES/governor.lua, src/SCRIPTS/RF/PAGES/motors.lua, src/SCRIPTS/RF/PAGES/profile.lua
Some minor tweaks to better match the Lua screens with the Configurator.
=> Screens now better match the Configurator

src/SCRIPTS/RF/PAGES/accelerometer.lua, src/SCRIPTS/RF/PAGES/profile.lua, src/SCRIPTS/RF/pages.lua, src/SCRIPTS/RF/ui.lua
Added an 'Accelerometer Trim' page. Also added support for negative 8 and 16 bit integer values.
=> Added 'Accelerometer Trim' page

src/SCRIPTS/RF/PAGES/governor.lua, src/SCRIPTS/RF/PAGES/profile.lua
Adjusted limits and added *TTA Filter Cutoff*.
=> Aligned with rotorflight-firmware 220419

src/SCRIPTS/RF/PAGES/profile.lua
-Gain limits aligned with firmware snapshot 220813.
-I-term limits can now be changed a lot quicker.
=> Profile page tweaks

.gitignore, bin/build.sh, src/SCRIPTS/RF/CMS/common.lua, src/SCRIPTS/RF/MSP/common.lua, src/SCRIPTS/RF/MSP/crsf.lua, src/SCRIPTS/RF/MSP/ghst.lua, src/SCRIPTS/RF/MSP/sp.lua, src/SCRIPTS/RF/PAGES/filters2.lua, src/SCRIPTS/RF/PAGES/pid_advanced.lua, src/SCRIPTS/RF/PAGES/profiles.lua, src/SCRIPTS/RF/PAGES/pwm.lua, src/SCRIPTS/RF/PAGES/simplified_tuning.lua, src/SCRIPTS/RF/board_info.lua, src/SCRIPTS/RF/cms.lua, src/SCRIPTS/RF/pages.lua, src/SCRIPTS/RF/protocols.lua, src/SCRIPTS/RF/ui_init.lua, src/SCRIPTS/RF/vtx_tables.lua
Merged all Betaflight commits in master untill 2022-09-24. This includes some performance fixes and support for Ghost MSP.
=> Merged Betaflight code

src/SCRIPTS/RF2/PAGES/profile.lua, src/SCRIPTS/RF2/PAGES/profile_rescue.lua, src/SCRIPTS/RF2/PAGES/rates.lua
- Labels are now readable on small displays
- PID mode selection limited to MODE 1 and MODE 2
- Fixed wrong Rate selection
=> Various tweaks

src/SCRIPTS/RF2/PAGES/profile.lua
=> fix: error limits

src/SCRIPTS/RF2/PAGES/governor.lua, src/SCRIPTS/RF2/PAGES/profile.lua
Aligned MSP messages and screens with firmware.
=> chore: aligned with firmware

src/SCRIPTS/RF2/PAGES/filters.lua
The Filter page has now also been aligned with firmware 230508.
=> fix: filter page

src/SCRIPTS/RF2/PAGES/pids.lua, src/SCRIPTS/RF2/PAGES/profile.lua, src/SCRIPTS/RF2/PAGES/profile_governor.lua
Changes:
- Added *O-gains* to the *Profile - PIDs* page
- Added *Offset limits*, *B-term cut-offs* and *Cross coupling* to the *Profile - Various* page
- Added *Max throttle* to the *Profile - Governor page*
=> chore: aligned with firmware 20230909

src/SCRIPTS/RF2/PAGES/profile.lua, src/SCRIPTS/RF2/PAGES/rates.lua, src/SCRIPTS/RF2/ui.lua, src/SCRIPTS/RF2/ui_init.lua
Changes:
- Added Yaw Precomp Cutoff to the Profile - Various page
- Added roll/pitch/yaw/collective dynamics to the Rates page
=> feat: aligned with firmware 20240128

src/SCRIPTS/RF2/PAGES/servos.lua, src/SCRIPTS/RF2/pages.lua, src/SCRIPTS/RF2/ui.lua
=> feat: added Servos page

src/SCRIPTS/RF2/TEMPLATES/480x320.lua, src/SCRIPTS/RF2/radios.lua
Added 480x320 support for Jumper T15
=> feat: add 480x320 support

src/SCRIPTS/RF2/ui.lua
Rotating the rotary wheel faster will change values faster while editing
=> feat: faster scroll wheel

src/SCRIPTS/RF2/MSP/common.lua, src/SCRIPTS/RF2/MSP/mspGovernorConfig.lua, src/SCRIPTS/RF2/PAGES/governor.lua, src/SCRIPTS/RF2/ui.lua
Refactored the Governor page so it uses a newly introduced Governor API (see mspGovernorConfig.lua and #47)
=> chore: refactor Governor page

src/SCRIPTS/RF2/MSP/mspStatus.lua, src/SCRIPTS/RF2/PAGES/copy_profiles.lua
Refactored the Copy Profiles page so it uses a newly introduced Status API (see mspStatus.lua and #47
=> chore: refactored copy_profiles

src/SCRIPTS/RF2/MSP/mspServos.lua, src/SCRIPTS/RF2/PAGES/servos.lua
Refactored the Servos page so it uses the new Servo API (see mspServos.lua and #47). 
Also added servo override when changing _Servo center_.
=> feat: refactored Servo page and added servo override

src/SCRIPTS/RF2/MSP/mspQueue.lua, src/SCRIPTS/RF2/rf2.lua, src/SCRIPTS/RF2/ui.lua
=> feat: added warning message if save fails

src/SCRIPTS/RF2/COMPILE/scripts.lua, src/SCRIPTS/RF2/PAGES/experimental.lua, src/SCRIPTS/RF2/pages.lua
This is to support MSP_EXPERIMENTAL and MSP_SET_EXPERIMENTAL for tuning some raw bytes.
Tested on TX16s.
=> Add an experimental config page.

src/SCRIPTS/RF2/PAGES/esc_flyrotor.lua
Support esc governor, modify some parameter ranges.
=> Support ESC Governor

src/SCRIPTS/RF2/PAGES/esc_flyrotor.lua
The motor timing range is changed to limit the minimum value of PI to 1.
=> Modify the data range of FLYFOTOR ESC

src/SCRIPTS/RF2/PAGES/profile.lua
This is to support the [Tail precomp improvements](https://github.com/rotorflight/rotorflight-firmware/pull/186) in the firmware.
=> Add support for inertia precomp

src/SCRIPTS/RF2/PAGES/profile.lua
This field is in `Hz`. A value of 25 means 2.5Hz.
=> Scale inertia cutoff field

src/SCRIPTS/RF2/PAGES/esc_flyrotor.lua, src/SCRIPTS/RF2/PAGES/settings.lua, src/SCRIPTS/RF2/pages.lua
Added the "Other" parameter setting page for FLYROTOR ESC and added the display of ESC model.
=> Added "Other" parameter setting page for FLYROTOR ESC

src/SCRIPTS/RF2/MSP/mspEscFlyrotor.lua
Modify the option data range of FLYROTOR ESC.
=> Modify the option data range of FLYROTOR ESC.

src/SCRIPTS/RF2/MSP/mspEscFlyrotor.lua, src/SCRIPTS/RF2/PAGES/esc_flyrotor.lua, src/SCRIPTS/RF2/PAGES/settings.lua, src/SCRIPTS/RF2/background_init.lua
Modified FLYROTOR ESC parameters
=> Modified FLYROTOR ESC parameters
